/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_1;

import java.awt.Color;
import java.awt.Graphics;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import static java.lang.Thread.yield;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class lienzo extends javax.swing.JPanel implements Runnable{

    /**
     * Creates new form lienzo
     */
    int turno=0;
    int dim=0;
    int dim2=0;
    int filNodo=0;
    int colNodo=0;
    String[][] matriz= new String[20][20];
    Thread hilo;
    int fil,col,filS,colS;
    
    public lienzo() {
        Leer("matriz.txt",matriz,20);
        hilo = new Thread(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void Leer(String nombre,String[][] matriz,int n){
     try{
        FileReader fr = new FileReader(nombre);
        BufferedReader br = new BufferedReader(fr);
        String temp="";
        int i=0;
        //String[] arreglo = null;
        while(temp!=null){
            temp = br.readLine();
            String x;
            x = temp;
            if(x!=null){
                String []arreglo=x.split(" ");
                for(int j=0;j<n;j++){
                   matriz[i][j]=arreglo[j];
                   System.out.print(matriz[i][j]+" ");
                }
            }
            i+=1;
            System.out.print("\n");
          }
        }catch(IOException e){
            System.out.println(e.getCause());
        }
    }
    
    public void Escribir(){
        try{
            FileWriter fw = new FileWriter("matriz2.txt"); 
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            for(int i=0;i<matriz.length;i++){
                for(int j=0;j<matriz.length;j++){
                    pw.write(""+matriz[i][j]+" ");
                }
                pw.append("\n");
            }
            pw.close();
            bw.close();
        }catch(IOException e){
            System.out.println(e.getCause());
        }
    }
    
    
    @Override
    public void paint(Graphics g){
        removeAll();
        for(int i=0;i<20;i++){
            for(int j=0;j<20;j++){
                if(matriz[i][j].equals("1")){
                    g.setColor(Color.black);
                    g.fillRect(dim, dim2, 20, 20);
                    dim+=20;
                }else{
                     if(matriz[i][j].equals("2")){
                         g.setColor(Color.blue);
                         g.fillRect(dim, dim2, 20, 20);
                         dim+=20;
                         fil=i;
                         col=j;
                     }else{
                         if(matriz[i][j].equals("3")){
                             g.setColor(Color.GREEN);
                             g.fillRect(dim, dim2, 20, 20);
                             dim+=20;
                             filS=i;
                             colS=j;
                         }else{
                             if(matriz[i][j].equals("4")){
                               g.setColor(Color.RED);
                               g.fillRect(dim, dim2, 20, 20);
                               dim+=20;
                             }else{
                                 
                                    g.setColor(Color.black);
                                    g.drawRect(dim, dim2, 20, 20);
                                    dim+=20;
                                    
                             }
                     }
                 }   
                }
                
            }
            dim=0;
            dim2+=20;
        }
        dim=0;
        dim2=0;
    }
    
    
    
    public void inicio(){
        Escribir();
        hilo.start();
    }
    
    public boolean existeCamino(int fila, int columna){
        
         
        if (fila<0|| fila>=20 || columna<0 || columna>=20) {
            return false;
           }
        
     if (matriz[fila][columna].equals("1")||matriz[fila][columna].equals("2")) {   
         return false;
          
         }
     
     
       
     return true;
    }
    
    public boolean wallTracing(int fil, int col){
       
        boolean salida = false;
        
        
            try {
                Thread.sleep(100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(lienzo.class.getName()).log(Level.SEVERE, null, ex);
                }
            matriz[fil][col]="2";
            
            if(fil==filS&&col==colS){
                return true;
            }
        
            if(!salida){
                matriz[fil][col]="0";
                salida=existeBresenham(fil,col,filS,colS);
                if(salida){BresenhamDIJ(fil,col,filS,colS);}
                matriz[fil][col]="2";
                repaint();
                System.out.println("Bresenham = "+salida);
            }
            
         //izquierda
       
       
        
       //frente
       if (!salida&&existeCamino(fil, col+1)) {
           
           System.out.println("frente ("+fil+","+(col+1)+")");  
            repaint();
            salida=wallTracing(fil, col+1);
            
        }
       
       //derecha
       if (!salida&&existeCamino(fil+1, col)) {
           
           System.out.println("derecha ("+(fil+1)+","+col+")");  
            repaint();
            salida=wallTracing(fil+1, col);
            
        }
       
       //atras
       if (!salida&&existeCamino(fil, col-1)) {
           
           System.out.println("atras ("+fil+","+(col-1)+")");  
            repaint();
            salida=wallTracing(fil, col-1);
           
        }
          if (!salida&& existeCamino(fil-1, col)) {
           
            System.out.println("izquierda ("+(fil-1)+","+col+")");
            repaint();
            salida=wallTracing(fil-1, col);
             
        }  
            
        return salida;
    }
    
    public void waypointNavigation(){
     
    int d1=0,d2=0,con1=30,con2=30,num1=0,num2=0,numeroNodos=0;
    String nodoInicio ="",nodoFin="";
        for(int i=0;i<20;i++){
            for(int j=0;j<20;j++){
            if(!matriz[i][j].equals("0")&&!matriz[i][j].equals("1")&&!matriz[i][j].equals("2")&&!matriz[i][j].equals("3")){
                numeroNodos+=1;
                if(existeBresenham(fil, col, i, j)){
                    d1=(int)Math.sqrt(Math.pow((i-fil), 2)+Math.pow((j-col), 2));
                    if(d1<con1){
                        nodoInicio=matriz[i][j];
                        con1=d1;
                        filNodo=i;
                        colNodo=j;
                    }
                    
                }
                if(existeBresenham(filS, colS, i, j)){
                    d2=(int)Math.sqrt(Math.pow((i-filS), 2)+Math.pow((j-colS), 2));
                    if(d2<con2){
                        nodoFin=matriz[i][j];
                        con2=d2;
                    }
                    
                }
                
            }
        }
        }
        
        System.out.println("nodo inicio: "+nodoInicio+" fil: "+filNodo+" col: "+colNodo);
        System.out.println("nodo final: "+nodoFin);
        System.out.println("número de nodos: "+numeroNodos);
        
        String arreglo[][]= new String[numeroNodos][numeroNodos+1];
        Leer("MatrizCamino.txt",arreglo,numeroNodos+1);
        int colV=0;
        for(int i=0;i<numeroNodos;i++){
            if(arreglo[i][0].equals(nodoInicio)){
                num1=i;
           
            }  if(arreglo[i][0].equals(nodoFin)){
                    num2=i;
                    colV=i+1;
                }
            
        }
        
        int p=1;
        System.out.println(num1+"-"+num2);
        String camino=nodoInicio;
        String paso=arreglo[num1][colV];
            camino+=paso;
            for(int i=0;i<numeroNodos;i++){
            if(arreglo[i][0].equals(paso)){
                paso=arreglo[i][colV];
                camino+=paso;
            }
            if(!paso.equals("-")&&i==(numeroNodos-1)){
                i=-1;
            }
            
        }
            System.out.println(camino);
        BresenhamDIJ(fil, col, filNodo,colNodo);
        
        /*if(num1==num2){
            BresenhamDIJ(fil, col, filNodo, colNodo);
            BresenhamDIJ(filNodo,colNodo,filS,colS);
        }else{
            aux(numeroNodos, nodoInicio, nodoFin, arreglo, camino, p);
        }*/
        
        if(num1<num2){
            
            //int p=1;
            String m=String.valueOf(camino.toCharArray()[p]);
            int n=camino.length();
            n=n-1;
            //BresenhamDIJ(fil, col, filNodo,colNodo);
            for(int k=0;k<20;k++){
                for(int j=0;j<20;j++){
                    if(matriz[k][j].equals(m)&&p<n){
                        p+=1;
                        m=String.valueOf(camino.toCharArray()[p]);
                        BresenhamDIJ(filNodo, colNodo, k, j);
                        filNodo=k;
                        colNodo=j;
                    }else{
                        if(p>=n){
                            j=20;
                            k=20;
                        }
                    }
                }
            }
            for(int k=19;k>=0;k--){
                for(int j=19;j>=0;j--){
                    
                    if(matriz[k][j].equals(m)&&p<n){
                        p+=1;
                        m=String.valueOf(camino.toCharArray()[p]);
                        BresenhamDIJ(filNodo, colNodo, k, j);
                        filNodo=k;
                        colNodo=j;
                    }else{
                        if(p>=n){
                            j=-1;
                            k=-1;
                        }
                    }
                }
            }
            for(int k=0;k<20;k++){
                for(int j=0;j<20;j++){
                    if(matriz[k][j].equals(m)&&p<n){
                        p+=1;
                        m=String.valueOf(camino.toCharArray()[p]);
                        BresenhamDIJ(filNodo, colNodo, k, j);
                        filNodo=k;
                        colNodo=j;
                    }else{
                        if(p>=n){
                            j=20;
                            k=20;
                        }
                    }
                }
            }
            for(int k=19;k>=0;k--){
                for(int j=19;j>=0;j--){
                    
                    if(matriz[k][j].equals(m)&&p<n){
                        p+=1;
                        m=String.valueOf(camino.toCharArray()[p]);
                        BresenhamDIJ(filNodo, colNodo, k, j);
                        filNodo=k;
                        colNodo=j;
                    }else{
                        if(p>=n){
                            j=-1;
                            k=-1;
                        }
                    }
                }
            }
            BresenhamDIJ(filNodo, colNodo, filS,colS);
            System.out.println(camino.toCharArray());
        }else{
            if(num1>num2){
                
            //int p=1;
            String m=String.valueOf(camino.toCharArray()[p]);
            int n=camino.length();
            n=n-1;
            
            for(int k=19;k>=0;k--){
                for(int j=19;j>=0;j--){
                    
                    if(matriz[k][j].equals(m)&&p<n){
                        p+=1;
                        m=String.valueOf(camino.toCharArray()[p]);
                        BresenhamDIJ(filNodo, colNodo, k, j);
                        filNodo=k;
                        colNodo=j;
                    }
                }
            }
            for(int k=0;k<20;k++){
                for(int j=0;j<20;j++){
                    if(matriz[k][j].equals(m)&&p<n){
                        p+=1;
                        m=String.valueOf(camino.toCharArray()[p]);
                        BresenhamDIJ(filNodo, colNodo, k, j);
                        filNodo=k;
                        colNodo=j;
                    }else{
                        if(p>=n){
                            j=20;
                            k=20;
                        }
                    }
                }
            }
            for(int k=19;k>=0;k--){
                for(int j=19;j>=0;j--){
                    
                    if(matriz[k][j].equals(m)&&p<n){
                        p+=1;
                        m=String.valueOf(camino.toCharArray()[p]);
                        BresenhamDIJ(filNodo, colNodo, k, j);
                        filNodo=k;
                        colNodo=j;
                    }
                }
            }
            for(int k=0;k<20;k++){
                for(int j=0;j<20;j++){
                    if(matriz[k][j].equals(m)&&p<n){
                        p+=1;
                        m=String.valueOf(camino.toCharArray()[p]);
                        BresenhamDIJ(filNodo, colNodo, k, j);
                        filNodo=k;
                        colNodo=j;
                    }else{
                        if(p>=n){
                            j=20;
                            k=20;
                        }
                    }
                }
            }
            BresenhamDIJ(filNodo, colNodo, filS,colS);
                System.out.println(camino);
        }else{
                if(num1==num2){
                    BresenhamDIJ(fil, col, filNodo, colNodo);
                    BresenhamDIJ(filNodo,colNodo,filS,colS);
                }
            }
        
        
    }
        
  }
    
    
    public void BresenhamDIJ(int x0, int y0, int x1, int y1) {
             
  int x, y, dx, dy, p, incE, incNE, stepx, stepy,con,con2;
  dx = (x1 - x0);
  dy = (y1 - y0);

 /* determinar que punto usar para empezar, cual para terminar */
  if (dy < 0) { 
    dy = -dy;  
    stepy = -1; 
  } 
  else {
    stepy = 1; 
  }

  if (dx < 0) {  
    dx = -dx;  
    stepx = -1; 
  } 
  else {
    stepx = 1;
  }

  x = x0;
  con=x;
  y = y0;
  con2=y;
 
  matriz[x0][y0]="4";
  repaint();
 /* se cicla hasta llegar al extremo de la línea */
  if(dx>dy){//no,
    p = 2*dy - dx; 
    incE = 2*dy; 
    incNE = 2*(dy-dx); 
    while (x != x1){
        try {
            Thread.sleep(50);
        } catch (InterruptedException ex) {
            Logger.getLogger(lienzo.class.getName()).log(Level.SEVERE, null, ex);
        }
        con=x;
      x = x + stepx;
      if(con<x){matriz[x][y]="4";repaint();}
      if (p < 0){
        p = p + incE;
      }
      else {
          con =y;
        y = y + stepy;
        p = p + incNE;
      }
      
      matriz[x][y]="4";
      repaint();
    }
    
  }
  else{
    p = 2*dx - dy; 
    incE = 2*dx; 
    incNE = 2*(dx-dy);
    while (y != y1){
        try {
            Thread.sleep(50);
        } catch (InterruptedException ex) {
            Logger.getLogger(lienzo.class.getName()).log(Level.SEVERE, null, ex);
        }
        con2=y-1;
      if(con<x){matriz[x][con2]="4";con=x;repaint();}else{
          if(con>x){matriz[con][y]="4";con=x;repaint();}
      }
      y = y + stepy;
      if (p < 0){
        p = p + incE;
      }
      else {
        con=x;  
        x = x + stepx;
        p = p + incNE;
      }
      if(y==y1&&con<x){
          matriz[x][y-1]="4";repaint();
      }else{
          if(y==y1&&con>x){matriz[con][y]="4";repaint();}
      }
    matriz[x][y]="4";
    repaint();
    }
    
    
  }
  
  }
    
    public boolean existeBresenham(int x0, int y0, int x1, int y1) {
        boolean eqv=false;
        int x, y, dx, dy, p, incE, incNE, stepx, stepy,con,con2;
        dx = (x1 - x0);
        dy = (y1 - y0);
/* determinar que punto usar para empezar, cual para terminar */
  if (dy < 0) { 
    dy = -dy;  
    stepy = -1; 
  } 
  else {
    stepy = 1;
  }

  if (dx < 0) {  
    dx = -dx;  
    stepx = -1; 
  } 
  else {
    stepx = 1;
  }
  x = x0;
  con=x;
  y = y0;
  con2=y;
  eqv=true;
 /* se cicla hasta llegar al extremo de la línea */
  if(dx>dy){
    p = 2*dy - dx; 
    incE = 2*dy; 
    incNE = 2*(dy-dx); 
    while (x != x1){
        con=x; 
      x = x + stepx;
      if(con<x&&!matriz[x][y].equals("1")&&!matriz[x][y].equals("2")){eqv=true;}
      if (p < 0){
        p = p + incE;
      }
      else {
          con =y;
        y = y + stepy;
        p = p + incNE;
      }
      if((!matriz[x][y].equals("1")&&!matriz[x][y].equals("2"))||matriz[x][y].equals("3")){eqv=true;}else{eqv=false;x=x1;};
    }
  }
  else{
    p = 2*dx - dy; 
    incE = 2*dx;
    incNE = 2*(dx-dy);
    while (y != y1){
        con2=y-1;
      if(con<x&&!matriz[x][con2].equals("1")&&!matriz[x][con2].equals("2")){con=x;eqv=true;}else{
          if(con>x&&!matriz[con][y].equals("1")&&!matriz[con][y].equals("2")){con=x;eqv=true;}else{
              if(con==x){eqv=true;}else{eqv=false;}
          }
      }
      
      y = y + stepy;
      if (p < 0){
        p = p + incE;
      }
      else {
        con=x;  
        x = x + stepx;
        p = p + incNE;
      }
      if(y==y1&&con<x&&!matriz[x][y-1].equals("1")&&!matriz[x][y-1].equals("2")&&eqv){
          }else{
          if(y==y1&&con>x&&!matriz[con][y].equals("1")&&!matriz[con][y].equals("2")&&eqv){}
      }
    if(!matriz[x][y].equals("1")&&!matriz[x][y].equals("2")&&eqv||matriz[x][y].equals("3")&&eqv){eqv=true;}else{eqv=false;y=y1;};
    }
  }
  return eqv;
    }
    
   public void inicio2(){
       turno=1;
       hilo.start();
   }
    
   public void aux(int numeroNodos,String nodoInicio,String nodoFin,String arreglo[][],String camino,int p){
       
       int num1=0,num2=0;
       for(int i=0;i<numeroNodos;i++){
            if(arreglo[i][0].equals(nodoInicio)){
                num1=i;
            }else{
                if(arreglo[i][0].equals(nodoFin)){
                    num2=i;
                }
            } 
        }   
       if(num1<num2){
            String m=String.valueOf(camino.toCharArray()[p]);
            int n=camino.length();
            n=n-1;
            for(int k=0;k<20;k++){
                for(int j=0;j<20;j++){
                    if(matriz[k][j].equals(m)&&p<n){
                        p+=1;
                        m=String.valueOf(camino.toCharArray()[p]);
                        BresenhamDIJ(filNodo, colNodo, k, j);
                        filNodo=k;
                        colNodo=j;
                        nodoInicio=matriz[k][j];
                        nodoFin=m;
                    }
                   }
            }
            System.out.println(nodoFin);
            if(!nodoFin.equals("-")){
                aux(numeroNodos,nodoInicio,nodoFin,arreglo,camino,p);
            }
            
        }else{
           if(num1>num2){
 
            String m=String.valueOf(camino.toCharArray()[p]);
            int n=camino.length();
            n=n-1;
            for(int k=19;k>=0;k--){
                for(int j=19;j>=0;j--){
                    
                    if(matriz[k][j].equals(m)&&p<n){
                        p+=1;
                        m=String.valueOf(camino.toCharArray()[p]);
                        BresenhamDIJ(filNodo, colNodo, k, j);
                        filNodo=k;
                        colNodo=j;
                        nodoInicio=matriz[k][j];
                        nodoFin=m;
                    }
                }
            }
            System.out.println(nodoFin);
            if(!nodoFin.equals("-")){
                System.out.println("Queeeeee");
                aux(numeroNodos,nodoInicio,nodoFin,arreglo,camino,p);
            }
           }
       }
       
   }
   
   
    @Override
    public void run() {
        
        if(turno==1){
            waypointNavigation();
            JOptionPane.showMessageDialog(this, "Has llegado a la meta");
        }else{
        if (wallTracing(fil, col)) {
            JOptionPane.showMessageDialog(this, "Has llegado a la meta");
        }
        else{
        
        JOptionPane.showMessageDialog(this, "No hay meta");
        
        }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
